### ISSUE TITLE
roscore error on Windows

### ISSUE THREAD

**Issue by traversaro** [RoboStack/ros-noetic#12]
If I install rviz with: 
~~~
conda install ros-noetic-rviz -c robostack
~~~

Then if I try `roscore`, it fails with error: 
![roscore_error](https://user-images.githubusercontent.com/1857049/100383252-7af51900-301d-11eb-875b-1be856002fb1.PNG)

**Comment by traversaro** [comment]
Env info:

~~~
(ros-tests) C:\Users\STraversaro>conda info

     active environment : ros-tests
    active env location : C:\Users\STraversaro\Miniforge3\envs\ros-tests
            shell level : 1
       user config file : C:\Users\STraversaro\.condarc
 populated config files : C:\Users\STraversaro\Miniforge3\.condarc
                          C:\Users\STraversaro\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.6.final.0
       virtual packages : __cuda=10.2=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\STraversaro\Miniforge3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/msys2/win-64
                          https://conda.anaconda.org/msys2/noarch
          package cache : C:\Users\STraversaro\Miniforge3\pkgs
                          C:\Users\STraversaro\.conda\pkgs
                          C:\Users\STraversaro\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\STraversaro\Miniforge3\envs
                          C:\Users\STraversaro\.conda\envs
                          C:\Users\STraversaro\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.8.6 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


(ros-tests) C:\Users\STraversaro>conda list
# packages in environment at C:\Users\STraversaro\Miniforge3\envs\ros-tests:
#
# Name                    Version                   Build  Channel
apr                       1.6.5                ha89961a_2    conda-forge
assimp                    5.0.1                h7d0832f_4    conda-forge
bcrypt                    3.2.0            py36h779f372_1    conda-forge
boost                     1.72.0           py36h9956518_1    conda-forge
boost-cpp                 1.72.0               h54f0996_4    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.11.8            h5b45459_0    conda-forge
catkin_pkg                0.4.23             pyh9f0ad1d_0    conda-forge
certifi                   2020.11.8        py36ha15d459_0    conda-forge
cffi                      1.14.4           py36he58ceb7_0    conda-forge
cmake                     3.19.1               h39d44d4_0    conda-forge
console_bridge            1.0.1                h7ef1ec2_0    conda-forge
cryptography              3.2.1            py36he58ceb7_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distro                    1.5.0              pyh9f0ad1d_0    conda-forge
docutils                  0.16             py36hd36e781_2    conda-forge
eigen                     3.3.8                h2d74725_0    conda-forge
empy                      3.3.4              pyh9f0ad1d_1    conda-forge
expat                     2.2.9                h33f27b4_2    conda-forge
freeimage                 3.18.0               h33f27b4_0    conda-forge
freetype                  2.10.4               h546665d_0    conda-forge
gettext                   0.19.8.1          hfbb10ce_1004    conda-forge
gmock                     1.10.0               h57928b3_4    conda-forge
gtest                     1.10.0               h5362a0b_4    conda-forge
icu                       67.1                 h33f27b4_0    conda-forge
ilmbase                   2.5.3                h7bd577a_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
libapr                    1.6.5                he774522_2    conda-forge
libapriconv               1.2.2                he774522_2    conda-forge
libaprutil                1.6.1                hcf73f5b_2    conda-forge
libblas                   3.8.0                    21_mkl    conda-forge
libcblas                  3.8.0                    21_mkl    conda-forge
libclang                  10.0.1          default_hf44288c_1    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libglib                   2.66.3               h35efcdc_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.8.0                    21_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
log4cxx                   0.11.0               hbd89bf9_1    conda-forge
lz4                       3.1.1            py36ha30e85c_0    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1
netifaces                 0.10.9          py36h779f372_1003    conda-forge
nose                      1.3.7                   py_1006    conda-forge
numpy                     1.19.4           py36hd1b969e_1    conda-forge
ogre                      1.10.12              h71cedee_6    conda-forge
openexr                   2.5.3                h5dfd299_0    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
orocos-kdl                1.4.0                h33f27b4_0    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pkg-config                0.29.2            h2bf4dc2_1008    conda-forge
poco                      1.9.0             hdef9aff_2003    conda-forge
pugixml                   1.10                 ha925a31_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycryptodome              3.9.9            py36h68aa20f_0    conda-forge
pycryptodomex             3.9.9            py36h68aa20f_0    conda-forge
pynacl                    1.4.0            py36h3a74357_2    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py36h003fed8_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
python                    3.6.11          h6f26aa1_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-gnupg              0.4.6              pyh9f0ad1d_0    conda-forge
python-orocos-kdl         1.4.0            py36h003fed8_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pyyaml                    5.3.1            py36hc753bc4_1    conda-forge
qt                        5.12.9               hb2cf2c5_0    conda-forge
ros-noetic-actionlib      1.13.2           py36hd49e2f0_2    robostack
ros-noetic-actionlib-msgs 1.13.0           py36h003fed8_2    robostack
ros-noetic-angles         1.9.13           py36h003fed8_2    robostack
ros-noetic-catkin         0.8.8            py36h003fed8_2    robostack
ros-noetic-class-loader   0.5.0            py36h576c775_2    robostack
ros-noetic-cpp-common     0.7.2            py36he1db51f_2    robostack
ros-noetic-gencpp         0.6.5            py36h003fed8_2    robostack
ros-noetic-geneus         3.0.0            py36h003fed8_2    robostack
ros-noetic-genlisp        0.4.18           py36h003fed8_2    robostack
ros-noetic-genmsg         0.5.16           py36h003fed8_2    robostack
ros-noetic-gennodejs      2.0.2            py36h003fed8_2    robostack
ros-noetic-genpy          0.6.14           py36h003fed8_2    robostack
ros-noetic-geometry-msgs  1.13.0           py36h003fed8_2    robostack
ros-noetic-image-transport 1.12.0           py36h003fed8_2    robostack
ros-noetic-interactive-markers 1.12.0           py36h003fed8_2    robostack
ros-noetic-laser-geometry 1.6.5            py36h799e0b3_2    robostack
ros-noetic-map-msgs       1.14.0           py36h003fed8_2    robostack
ros-noetic-media-export   0.3.0            py36h003fed8_2    robostack
ros-noetic-message-filters 1.15.8           py36hd49e2f0_2    robostack
ros-noetic-message-generation 0.4.1            py36h003fed8_2    robostack
ros-noetic-message-runtime 0.4.13           py36h003fed8_2    robostack
ros-noetic-nav-msgs       1.13.0           py36h003fed8_2    robostack
ros-noetic-pluginlib      1.13.0           py36hd49e2f0_2    robostack
ros-noetic-python-qt-binding 0.4.3            py36h6d31c09_2    robostack
ros-noetic-resource-retriever 1.12.6           py36hfea984b_2    robostack
ros-noetic-ros-environment 1.3.1            py36h003fed8_2    robostack
ros-noetic-rosbag         1.15.8           py36hea6d0d7_2    robostack
ros-noetic-rosbag-storage 1.15.8           py36hd1294b3_2    robostack
ros-noetic-rosbash        1.15.6           py36h003fed8_2    robostack
ros-noetic-rosbuild       1.15.6           py36h003fed8_2    robostack
ros-noetic-rosclean       1.15.6           py36h003fed8_2    robostack
ros-noetic-rosconsole     1.14.2           py36hd49e2f0_2    robostack
ros-noetic-rosconsole-bridge 0.5.4            py36h254838c_2    robostack
ros-noetic-roscpp         1.15.8           py36hd49e2f0_2    robostack
ros-noetic-roscpp-serialization 0.7.2            py36h003fed8_2    robostack
ros-noetic-roscpp-traits  0.7.2            py36h003fed8_2    robostack
ros-noetic-rosgraph       1.15.8           py36h003fed8_2    robostack
ros-noetic-rosgraph-msgs  1.11.3           py36h003fed8_2    robostack
ros-noetic-roslaunch      1.15.8           py36h003fed8_2    robostack
ros-noetic-roslib         1.15.6           py36hd49e2f0_2    robostack
ros-noetic-roslz4         1.15.8           py36h003fed8_2    robostack
ros-noetic-rosmaster      1.15.8           py36h003fed8_2    robostack
ros-noetic-rosmsg         1.15.8           py36h003fed8_2    robostack
ros-noetic-rosnode        1.15.8           py36h003fed8_2    robostack
ros-noetic-rosout         1.15.8           py36h003fed8_2    robostack
ros-noetic-rospack        2.6.2            py36hea6d0d7_2    robostack
ros-noetic-rosparam       1.15.8           py36h003fed8_2    robostack
ros-noetic-rospy          1.15.8           py36h003fed8_2    robostack
ros-noetic-rosservice     1.15.8           py36h003fed8_2    robostack
ros-noetic-rostest        1.15.8           py36hd49e2f0_2    robostack
ros-noetic-rostime        0.7.2            py36hd49e2f0_2    robostack
ros-noetic-rostopic       1.15.8           py36h003fed8_2    robostack
ros-noetic-rosunit        1.15.6           py36h003fed8_2    robostack
ros-noetic-roswtf         1.15.8           py36h003fed8_2    robostack
ros-noetic-rviz           1.14.1           py36h6d31c09_2    robostack
ros-noetic-sensor-msgs    1.13.0           py36h003fed8_2    robostack
ros-noetic-std-msgs       0.5.13           py36h003fed8_2    robostack
ros-noetic-std-srvs       1.11.3           py36h003fed8_2    robostack
ros-noetic-tf             1.13.2           py36h003fed8_2    robostack
ros-noetic-tf2            0.7.5            py36h254838c_2    robostack
ros-noetic-tf2-geometry-msgs 0.7.5            py36h003fed8_2    robostack
ros-noetic-tf2-msgs       0.7.5            py36h003fed8_2    robostack
ros-noetic-tf2-py         0.7.5            py36h003fed8_2    robostack
ros-noetic-tf2-ros        0.7.5            py36h003fed8_2    robostack
ros-noetic-topic-tools    1.15.8           py36h003fed8_2    robostack
ros-noetic-urdf           1.13.2           py36h003fed8_2    robostack
ros-noetic-visualization-msgs 1.13.0           py36h003fed8_2    robostack
ros-noetic-xmlrpcpp       1.15.8           py36hd49e2f0_2    robostack
rosdep                    0.20.0           py36ha15d459_0    conda-forge
rosdistro                 0.8.3            py36h9f0ad1d_1    conda-forge
rospkg                    1.2.9              pyhd3deb0d_0    conda-forge
ruby                      2.7.2                h8b1b97a_2    conda-forge
sdl2                      2.0.12               h0e60522_1    conda-forge
setuptools                49.6.0           py36hd36e781_2    conda-forge
sip                       4.19.20          py36h6538335_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               he774522_1    conda-forge
tinyxml                   2.6.2                h7ef1ec2_1    conda-forge
tinyxml2                  8.0.0                h33f27b4_1    conda-forge
tk                        8.6.10               he774522_1    conda-forge
urdfdom                   2.3.3                h7ef1ec2_0    conda-forge
urdfdom_headers           1.0.5                h7ef1ec2_2    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wincertstore              0.2             py36h9f0ad1d_1005    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yaml-cpp                  0.6.3                ha925a31_4    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge
zziplib                   0.13.69              ha81a0f5_1    conda-forge

(ros-tests) C:\Users\STraversaro>
~~~

**Comment by Tobias-Fischer** [comment]
Fixed by https://github.com/conda-forge/log4cxx-feedstock/pull/6

That should all work again after a rebuild 👍

**Comment by Tobias-Fischer** [comment]
Hey @traversaro - could you please test whether this works fine now? Closing in the meantime, please reopen if it's still an issue.

**Comment by traversaro** [comment]
I may be doing something wrong, but as far as I can see there are no new ros-noetic binaries in https://anaconda.org/robostack/repo , so I think the problem is still there. Perhaps it is necessary to comment out the `skip_existing` json parameter ( https://github.com/RoboStack/ros-noetic/blob/master/vinca_linux_64.yaml#L22 ) to force a mass rebuild, similar to what was done in https://github.com/RoboStack/ros-melodic by @wolfv ?

**Comment by Tobias-Fischer** [comment]
Ah yes I forgot that there's a new version as well. Need to wait for a rebuild indeed, sorry for the confusion..

**Comment by Tobias-Fischer** [comment]
Needs a new version of conda-build with rebuilt sip & pyqt, see conda-forge/conda-forge.github.io#1066 conda/conda-build#4126

**Comment by Tobias-Fischer** [comment]
This should be fixed with the recent rebuild. Could you please check @traversaro?
